version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - redis
    environment:
      - DB_URI=mongodb://mongo:27017/neuromnia
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"
